const taskContainer = document.querySelector(".task__container");

// global Store
const globalStore = [];

//card code
const newCard = ({
  id,
  imageUrl,
  taskTitle,
  taskDescription,
  taskType,
}) => `<div class="col-md-6 col-lg-4" id=${id}>
<div class="card">
  <div class="card-header d-flex justify-content-end gap-2">
    <button type="button" class="btn btn-outline-success">
      <i class="fas fa-pencil-alt"></i>
    </button>
    <button type="button" class="btn btn-outline-danger">
      <i class="fas fa-trash-alt"></i>
    </button>
  </div>
  <div class="card-body">
    <img
      src=${imageUrl}
      class="card-imp-top"
      alt="....."
    />
    <h5 class="card-title">${taskTitle}</h5>
    <p class="card-text">
      ${taskDescription}
    </p>
    <span class="badge bg-primary">${taskType}</span>
  </div>
  <div class="card-footer text-muted">
    <button type="button" class="btn btn-outline-primary float-end">
      Open Task
    </button>
  </div>
</div>`;

const loadInitialTaskCard = () => {
  // access local storage
  const getInitialData = localStorage.getItem("tasky");
  if (!getInitialData) return;
  // convert stringified object to object
  const { cards } = JSON.parse(getInitialData);

  // use map to generate HTML card
  cards.map((card) => {
    const createNewCard = newCard(card);
    taskContainer.insertAdjacentHTML("beforeend", createNewCard);
    globalStore.push(card);
  });
};

const saveChanges = () => {
  const taskData = {
    id: `${Date.now()}`, // Create Unique no. that generated by Date.now()function
    imageUrl: document.getElementById("imageurl").value,
    taskTitle: document.getElementById("tasktitle").value,
    taskType: document.getElementById("tasktype").value,
    taskDescription: document.getElementById("taskdescription").value,
  };
  const createNewCard = newCard(taskData);

  taskContainer.insertAdjacentHTML("beforeend", createNewCard);
  globalStore.push(taskData);

  //local storage API
  localStorage.setItem("tasky", JSON.stringify({ cards: globalStore }));
};
